# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 15:32

# Copyright (c) 2018 Josef Wachtler
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

'''
This is the initial database migration for the LTI consumer.
'''


from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLaunchParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('required', models.BooleanField(verbose_name='Required')),
            ],
            options={
                'verbose_name_plural': 'Default Launch Parameters',
                'verbose_name': 'Default Launch Parameter',
            },
        ),
        migrations.CreateModel(
            name='LaunchParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('value', models.CharField(blank=True, max_length=200, verbose_name='Value')),
            ],
            options={
                'verbose_name_plural': 'Launch Parameters',
                'verbose_name': 'Launch Parameter',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('launch_url', models.URLField(verbose_name='Launch URL')),
                ('consumer_key', models.CharField(blank=True, max_length=200, verbose_name='Consumer key')),
                ('consumer_secret', models.CharField(blank=True, max_length=200, verbose_name='Consumer secret')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
            ],
            options={
                'verbose_name_plural': 'Testcases',
                'verbose_name': 'Testcase',
            },
        ),
        migrations.AddField(
            model_name='launchparam',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Testcase', verbose_name='Testcase'),
        ),
    ]
